### PR TITLE
Issue #126. Added focus_on_load param

### PR DESCRIPTION
**Pull request by aka-nez**
Issue #126

### CODE REVIEW

**Comment by CGA1123** [comment]
Hey @aka-nez, thanks for this! Sorry for the delay in having a look!

Looks great, if you can update the CHANGELOG as well, as you mentioned in #126 that would be fantastic 😄

**Comment by aka-nez** [comment]
@CGA1123 done!

**Review by CGA1123 — APPROVED** [review]
Sorry about the delay in getting this merged! Thanks for you patience 🙇‍♂️

**Comment by CGA1123** [comment]
Released as [v0.20.0](https://github.com/CGA1123/slack-ruby-block-kit/releases/tag/v0.20.0) 🚀

**Pull request merged**
